cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'unrar'
brew 'vim'
brew 'Schniz/tap/fnm'
brew 'bat'
brew 'diff-so-fancy'
brew 'antigen'
brew 'git-delta'

cask 'google-chrome'
cask 'spotify'
cask 'iterm2'
cask 'slack'
